In [73]:
import numpy as np
import math

In [74]:
L, d_k, d_v = 4, 8, 8   # L-> size of input and d_v and d_k is length of vector
q = np.random.randn(L,d_k)   # what i am lookling for
k = np.random.randn(L,d_k)   # what i can offer
v = np.random.randn(L,d_v)   # what i actually offer


In [75]:
print('Q ',q,'\nK ',k,'\nV ',v)

Q  [[ 0.13835544  0.05302069 -1.92056396 -0.41408459 -0.90817973  0.95487426
   0.09066509 -0.83239626]
 [-0.58171481  1.02591346  0.12084231 -0.28284516 -0.31526041  1.02373095
   0.3095154   0.60866634]
 [-0.83997612  0.17209111  0.58317121 -0.7895387   0.54820306  0.53428
   0.39383483  0.95668413]
 [ 1.40365343 -0.14056982  0.20769021 -0.34202094 -0.91800571 -1.59050277
  -0.76118562  0.26963971]] 
K  [[-0.60717842  0.69754786 -1.45232277  0.21975905 -0.31690028  0.02860548
   0.80309597 -2.02521947]
 [-1.09924128  0.3204701  -0.93089215 -1.22689331 -2.48123274 -0.32521921
  -0.12317847 -0.09667761]
 [-0.85188565 -0.09358945 -0.48384823  0.93090039  0.5680219   1.22635384
  -0.54950555 -0.04131698]
 [-1.54796687  0.45822898 -0.72845734 -0.35873565  0.12729905  1.79042244
  -1.06175841  1.29584968]] 
V  [[ 0.18039911 -0.75172325  0.25897613  0.86573161  0.64354282 -0.46825087
  -1.53045598 -1.63294178]
 [-0.36924828 -0.8889616   0.25361375 -0.13002521 -0.67815793  0.1080676
   0.599

In [76]:
np.matmul(q,k.T)

array([[ 4.7249729 ,  4.17294896,  1.06068365,  1.77681484],
       [-0.02375334,  1.55507663,  0.95892269,  3.63690472],
       [-2.17005448, -0.27068267,  0.39297539,  3.08546666],
       [-2.23908317,  1.50102523, -3.66630582, -4.07274586]])

In [77]:
 #why we need sqrt(d_k) in denominator
q.var(),k.var(), np.matmul(q,k.T).var()

(0.5906333774021342, 0.9100498619054902, 6.596802896569788)

In [78]:
scaled = np.matmul(q,k.T)//math.sqrt(d_k)
q.var(),k.var(), scaled.var()

(0.5906333774021342, 0.9100498619054902, 0.9375)

In [79]:
scaled

array([[ 1.,  1.,  0.,  0.],
       [-1.,  0.,  0.,  1.],
       [-1., -1.,  0.,  1.],
       [-1.,  0., -2., -2.]])

## Masking

In [80]:
mask = np.tril(np.ones((L,L)))
mask

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [81]:
mask[mask == 0] = -np.infty
mask[mask == 1] = 0
mask

array([[  0., -inf, -inf, -inf],
       [  0.,   0., -inf, -inf],
       [  0.,   0.,   0., -inf],
       [  0.,   0.,   0.,   0.]])

In [82]:
scaled + mask

array([[  1., -inf, -inf, -inf],
       [ -1.,   0., -inf, -inf],
       [ -1.,  -1.,   0., -inf],
       [ -1.,   0.,  -2.,  -2.]])

## softmax

In [83]:
def softmax_extra(x):
    """Compute softmax values for each sets of scores in x."""
    return np.exp(x) / np.sum(np.exp(x), axis=0)

def softmax(x):
    return (np.exp(x).T / np.sum(np.exp(x), axis = -1)).T


In [84]:
attention = softmax(scaled + mask)
attention

array([[1.        , 0.        , 0.        , 0.        ],
       [0.26894142, 0.73105858, 0.        , 0.        ],
       [0.21194156, 0.21194156, 0.57611688, 0.        ],
       [0.22451524, 0.61029569, 0.08259454, 0.08259454]])

In [85]:
new_v = np.matmul(attention,v)
new_v

array([[ 0.18039911, -0.75172325,  0.25897613,  0.86573161,  0.64354282,
        -0.46825087, -1.53045598, -1.63294178],
       [-0.22142533, -0.85205253,  0.25505592,  0.13777504, -0.32269785,
        -0.04692831,  0.02690159,  0.17904796],
       [ 0.49338567, -1.2308856 , -0.17393953,  0.55011192,  0.25178733,
         0.30480377,  0.56881162, -0.78104869],
       [-0.04193318, -0.67222829,  0.08000057,  0.10341854, -0.160125  ,
        -0.17409209,  0.18353933,  0.14644743]])

In [86]:
v

array([[ 0.18039911, -0.75172325,  0.25897613,  0.86573161,  0.64354282,
        -0.46825087, -1.53045598, -1.63294178],
       [-0.36924828, -0.8889616 ,  0.25361375, -0.13002521, -0.67815793,
         0.1080676 ,  0.59982142,  0.84564174],
       [ 0.92587229, -1.53294639, -0.49048837,  0.68421039,  0.44977628,
         0.66156987,  1.32968115, -1.0660807 ],
       [ 0.80444915,  2.00603411, -1.11885402, -0.8246261 ,  0.87315245,
        -2.29504141,  0.62058808,  1.02947091]])

In [87]:
import numpy as np
import math

L, d_k, d_v = 4, 8, 8   # L-> size of input and d_v and d_k is length of vector
q = np.random.randn(L,d_k)   # what i am lookling for
k = np.random.randn(L,d_k)   # what i can offer
v = np.random.randn(L,d_v)   # what i actually offer
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x), axis=0)

def mask():
    maskMat = np.tril(np.ones((L,L)))
    maskMat[maskMat == 0] = -np.infty
    maskMat[maskMat == 1] = 0
    return maskMat

def scaled_dot_product_attention(q,k,v, mask=None):
    d_k = q.shape[-1]
    scaled = np.matmul(q,k.T) / math.sqrt(d_k)
    if mask is not None:
        scaled =  scaled + mask()
    
    attention = softmax(scaled)

    out = np.matmul(attention, v)
    return out,attention

In [88]:
import torch
import torch.nn as nn
import torch.nn.functional as F

sequence_length = 4 # my name is ajay
batch_size = 1 # helps in parrallel processing
input_dim = 512 # vector input goes to attention 
d_model = 512 #  output of attention unit for every single words
x = torch.randn(batch_size, sequence_length, input_dim)

In [89]:
print(x.type)
x.shape

<built-in method type of Tensor object at 0x12ec10640>


torch.Size([1, 4, 512])

In [90]:
qkv_layer = nn.Linear(input_dim, 3*d_model)

In [91]:
qkv_layer

Linear(in_features=512, out_features=1536, bias=True)

In [92]:

## Creating an object for the linear class
linear_layer = nn.Linear(in_features=5, out_features=1)
linear_layer    

# input = (*, in_feature)   
# output = (*, out_feature)  
# bias = out_feature
# weight matrix = in_feature * out_feature

Linear(in_features=5, out_features=1, bias=True)

In [93]:
## Passing input to the linear layer
# x = (torch.arange(20),dtype = torch.float32).view(4,5)
x = torch.arange((5),dtype = torch.float32).view(1,5)
x

tensor([[0., 1., 2., 3., 4.]])

In [94]:
print(linear_layer.weight)
print(linear_layer.bias)

Parameter containing:
tensor([[-0.1490,  0.1820, -0.4206, -0.1481,  0.3122]], requires_grad=True)
Parameter containing:
tensor([0.3018], requires_grad=True)


In [95]:
linear_layer(x)

tensor([[0.4471]], grad_fn=<AddmmBackward0>)

# multihead attention

In [96]:
import torch
import torch.nn as nn
import torch.nn.functional as F

sequence_length = 4 # my name is ajay
batch_size = 1 # helps in parrallel processing
input_dim = 512 # vector input goes to attention    ### after positional encoding
d_model = 512 #  output of attention unit for every single words
x = torch.randn(batch_size, sequence_length, input_dim)

In [97]:
x.shape

torch.Size([1, 4, 512])

In [98]:
qkv_layer = nn.Linear(input_dim, 3*d_model)    # for each q,k,v

In [99]:
qkv = qkv_layer(x )
qkv.shape

torch.Size([1, 4, 1536])

In [100]:
nums_heads = 8
head_dim = d_model // nums_heads
qkv = qkv.reshape(batch_size, sequence_length, nums_heads, 3*head_dim)  # 3 becuase it is combination of q,k,v vector
qkv.shape

torch.Size([1, 4, 8, 192])

In [101]:
qkv = qkv.permute(0,2,1,3)
qkv.shape

torch.Size([1, 8, 4, 192])

In [102]:
# breaking down qkv vector into individual by last dimention
q,k,v = qkv.chunk(3, dim = -1)
q.shape, k.shape, v.shape

(torch.Size([1, 8, 4, 64]),
 torch.Size([1, 8, 4, 64]),
 torch.Size([1, 8, 4, 64]))

In [103]:
d_k = q.size()[-1]
scaled = torch.matmul(q, k.transpose(-2,-1))/math.sqrt(d_k)
scaled.shape    # basically our sequence length
    

torch.Size([1, 8, 4, 4])

## masking

In [104]:
mask = torch.full(scaled.size() , float('-inf'))
mask = torch.triu(mask, diagonal=1)
mask[0][1]

tensor([[0., -inf, -inf, -inf],
        [0., 0., -inf, -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., 0.]])

In [105]:
(scaled + mask)[0][1]

tensor([[ 0.3939,    -inf,    -inf,    -inf],
        [-0.1757, -0.2276,    -inf,    -inf],
        [ 0.7108, -0.1185, -0.0219,    -inf],
        [ 0.2490, -0.0359,  0.2940, -0.4631]], grad_fn=<SelectBackward0>)

In [106]:
scaled +=mask

In [107]:
attention = F.softmax(scaled, dim=-1)
attention[0][1]

tensor([[1.0000, 0.0000, 0.0000, 0.0000],
        [0.5130, 0.4870, 0.0000, 0.0000],
        [0.5217, 0.2276, 0.2507, 0.0000],
        [0.3041, 0.2287, 0.3181, 0.1492]], grad_fn=<SelectBackward0>)

In [108]:
value = torch.matmul(attention, v)
value.shape

torch.Size([1, 8, 4, 64])

In [109]:
import math

def scaled_dot_product(q, k, v, mask = None):
    d_k = q.size()[-1]
    scaled = torch.matmul(q, k.transpose(-2,-1)) / math.sqrt(d_k)
    if mask is not None:
        scaled +=mask
    
    attention = F.softmax(scaled, dim = -1)
    values = torch.matmul(attention, v)

    return values, attention

In [110]:
values, attention = scaled_dot_product(q,k,v, mask = None)
values.shape , attention.shape

(torch.Size([1, 8, 4, 64]), torch.Size([1, 8, 4, 4]))

In [111]:
attention[0][1]

tensor([[0.3402, 0.1514, 0.2852, 0.2232],
        [0.1685, 0.1600, 0.2717, 0.3998],
        [0.3671, 0.1602, 0.1764, 0.2963],
        [0.3041, 0.2287, 0.3181, 0.1492]], grad_fn=<SelectBackward0>)

In [112]:
values, attention = scaled_dot_product(q,k,v, mask = mask)
values.shape , attention.shape

(torch.Size([1, 8, 4, 64]), torch.Size([1, 8, 4, 4]))

In [113]:
attention[0][1]

tensor([[1.0000, 0.0000, 0.0000, 0.0000],
        [0.5130, 0.4870, 0.0000, 0.0000],
        [0.5217, 0.2276, 0.2507, 0.0000],
        [0.3041, 0.2287, 0.3181, 0.1492]], grad_fn=<SelectBackward0>)

In [114]:
values = values.reshape(batch_size, sequence_length, nums_heads*head_dim)
values.shape

torch.Size([1, 4, 512])

In [115]:
linear_layer = nn.Linear(d_model, d_model)

# multihead dimention code

In [116]:
import math
class MultiheadAttention(nn.Module):
    def __init__(self, input_dim, d_model, nums_heads):
        super().__init__()
        self.input_dim = input_dim
        self.d_model = d_model
        self.nums_head = nums_heads
        self.head_dim = d_model // nums_heads
        self.qkv_layer = nn.Linear(input_dim, 3 * d_model)
        self.linear_layer = nn.Linear(d_model, d_model)

    def scaled_dot_product(self, q, k, v, mask = None):
        d_k = q.size()[-1]
        scaled = torch.matmul(q, k.transpose(-2,-1)) / math.sqrt(d_k)
        if mask is not None:
            scaled +=mask
        
        attention = F.softmax(scaled, dim = -1)
        values = torch.matmul(attention, v)
        return values, attention
    def forward(self, x, mask=None):
        batch_size, sequence_length, input_dim = x.size()
        qkv = self.qkv_layer(x)
        print("qkv shape: ", qkv.shape)
        qkv = qkv.reshape(batch_size, sequence_length, self.nums_head, 3 * self.head_dim)
        print("qkv shape: ", qkv.shape)
        qkv = qkv.permute(0,2,1,3)
        print("qkv shape: ", qkv.shape)
        q, k, v = qkv.chunk(3, dim = -1)
        print("q: ",q.shape, '\nk: ',k.shape, '\nv: ',v.shape)
        values, attention = self.scaled_dot_product(q,k,v, mask)
        print("values shape : ",values.shape)
        print("Attention shape : ",attention.shape)
        values = values.reshape(batch_size, sequence_length, self.nums_head * self.head_dim)
        print("values shape : ",values.shape)
        out = self.linear_layer(values)
        print("output shape : ",out.shape)
        return out



In [117]:
input_dim = 512
d_model =  512
nums_head = 8
batch_size = 1
sequence_length = 4
x = torch.randn(batch_size, sequence_length, input_dim)

model = MultiheadAttention(input_dim, d_model, nums_head)
put = model.forward(x)


qkv shape:  torch.Size([1, 4, 1536])
qkv shape:  torch.Size([1, 4, 8, 192])
qkv shape:  torch.Size([1, 8, 4, 192])
q:  torch.Size([1, 8, 4, 64]) 
k:  torch.Size([1, 8, 4, 64]) 
v:  torch.Size([1, 8, 4, 64])
values shape :  torch.Size([1, 8, 4, 64])
Attention shape :  torch.Size([1, 8, 4, 4])
values shape :  torch.Size([1, 4, 512])
output shape :  torch.Size([1, 4, 512])


# positional encoding

In [118]:
max_sequence_length = 4  # my seq length is 4 but defininng
d_model = 6         # actually 512 but for illustration purpose 6

In [119]:
even_i = torch.arange(0,d_model,2).float()
even_i

tensor([0., 2., 4.])

In [120]:
even_denominator = torch.pow(10000,even_i / d_model)
even_denominator

tensor([  1.0000,  21.5443, 464.1590])

In [121]:
odd_i = torch.arange(1,d_model,2).float()
odd_i

tensor([1., 3., 5.])

In [122]:
odd_denominator = torch.pow(10000,(odd_i -1 )/ d_model)
odd_denominator

tensor([  1.0000,  21.5443, 464.1590])

In [123]:
# we are using single denominator becoz odd and even both are same
denominator = torch.pow(10000,(odd_i -1 )/ d_model)   
denominator   

tensor([  1.0000,  21.5443, 464.1590])

In [124]:
even_i / denominator , odd_i / denominator

(tensor([0.0000, 0.0928, 0.0086]), tensor([1.0000, 0.1392, 0.0108]))

In [125]:
position = torch.arange(max_sequence_length,dtype=torch.float).reshape(max_sequence_length,1)
position

tensor([[0.],
        [1.],
        [2.],
        [3.]])

In [126]:
position/denominator , denominator

(tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.0000e+00, 4.6416e-02, 2.1544e-03],
         [2.0000e+00, 9.2832e-02, 4.3089e-03],
         [3.0000e+00, 1.3925e-01, 6.4633e-03]]),
 tensor([  1.0000,  21.5443, 464.1590]))

In [127]:
even_PE = torch.sin(position/denominator)
odd_PE = torch.cos(position/denominator)

even_PE , odd_PE

(tensor([[0.0000, 0.0000, 0.0000],
         [0.8415, 0.0464, 0.0022],
         [0.9093, 0.0927, 0.0043],
         [0.1411, 0.1388, 0.0065]]),
 tensor([[ 1.0000,  1.0000,  1.0000],
         [ 0.5403,  0.9989,  1.0000],
         [-0.4161,  0.9957,  1.0000],
         [-0.9900,  0.9903,  1.0000]]))

In [128]:
# joining both even_PE and odd_PE
stacked = torch.stack([even_PE, odd_PE], dim =2)
stacked

tensor([[[ 0.0000,  1.0000],
         [ 0.0000,  1.0000],
         [ 0.0000,  1.0000]],

        [[ 0.8415,  0.5403],
         [ 0.0464,  0.9989],
         [ 0.0022,  1.0000]],

        [[ 0.9093, -0.4161],
         [ 0.0927,  0.9957],
         [ 0.0043,  1.0000]],

        [[ 0.1411, -0.9900],
         [ 0.1388,  0.9903],
         [ 0.0065,  1.0000]]])

In [129]:
#falten this
PE = torch.flatten(stacked, start_dim=1, end_dim=2)
PE

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403,  0.0464,  0.9989,  0.0022,  1.0000],
        [ 0.9093, -0.4161,  0.0927,  0.9957,  0.0043,  1.0000],
        [ 0.1411, -0.9900,  0.1388,  0.9903,  0.0065,  1.0000]])

In [130]:
class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_sequence_length):
        super().__init__()
        self.d_model = d_model
        self.max_sequence_length = max_sequence_length
    
    def forward(self):
        even_i = torch.arange(0,self.d_model,2).float()
        odd_i = torch.arange(1,self.d_model,2).float()
        denominator = torch.pow(10000,(odd_i -1 )/ d_model)   
        position = torch.arange(self.max_sequence_length).reshape(self.max_sequence_length,1)
        even_PE = torch.sin(position / denominator)
        odd_PE = torch.cos(position / denominator)

        stacked = torch.stack([even_PE,odd_PE],dim = 2)
        PE = torch.flatten(stacked , start_dim=1, end_dim=2)
        return PE
        
        

In [131]:
model = PositionalEncoding(6,4)
PE = model.forward()
PE

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403,  0.0464,  0.9989,  0.0022,  1.0000],
        [ 0.9093, -0.4161,  0.0927,  0.9957,  0.0043,  1.0000],
        [ 0.1411, -0.9900,  0.1388,  0.9903,  0.0065,  1.0000]])

# Layer Normalization

In [132]:
inputs = torch.Tensor([[[0.2, 0.1, 0.3], [0.5, 0.1, 0.1]]])
B, S, E = inputs.size()
inputs = inputs.reshape(S, B, E)
inputs.size()   # number of words, batch size , embedding of each batch

torch.Size([2, 1, 3])

In [133]:
parameter_shape = inputs.size()[-2:]
gamma = nn.Parameter(torch.ones(parameter_shape))
beta = nn.Parameter(torch.zeros(parameter_shape))
print(parameter_shape)
gamma,beta

torch.Size([1, 3])


(Parameter containing:
 tensor([[1., 1., 1.]], requires_grad=True),
 Parameter containing:
 tensor([[0., 0., 0.]], requires_grad=True))

In [134]:
dims = [-(i + 1)for i in range(len(parameter_shape))]
dims

[-1, -2]

In [135]:
mean = inputs.mean(dim = dims, keepdim = True)
mean, mean.size()

(tensor([[[0.2000]],
 
         [[0.2333]]]),
 torch.Size([2, 1, 1]))

In [136]:
var = ((inputs - mean) ** 2).mean(dim = dims, keepdim = True)
epsilon = 1e-5
std = (var + epsilon).sqrt()
std

tensor([[[0.0817]],

        [[0.1886]]])

In [137]:
y = (inputs-mean)/std
y

tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]])

In [138]:
out = gamma * y + beta
out

tensor([[[ 0.0000, -1.2238,  1.2238]],

        [[ 1.4140, -0.7070, -0.7070]]], grad_fn=<AddBackward0>)

In [139]:
import torch.nn
class LayerNormalization():
    def __init__(self, parameter_shape, eps = 1e-5):
        self.parameter_shape = parameter_shape
        self.eps = eps
        self.gamma = nn.Parameter(torch.ones(parameter_shape))
        self.beta = nn.Parameter(torch.zeros(parameter_shape))

    def forward(self, input):
        dims = [-(i+1) for i in range(len(self.parameter_shape))]
        mean = inputs.mean(dim = dims, keepdim = True)
        print("Mean : ",mean.size(),mean)
        var = ((inputs-mean)**2).mean(dim = dims, keepdim = True)
        std = (var + self.eps).sqrt()
        print("STD: ",std.shape, std)
        y = (input - mean) / std

        print("y: ",y.shape,y)

        out = self.gamma * y + self.beta
        print("out: ",out.shape, out)
        
        return out

In [140]:
batch_size = 3
sentence_length = 5
embedding_dim = 8
inputs = torch.randn(sentence_length, batch_size, embedding_dim)
inputs.size(), inputs[0]

(torch.Size([5, 3, 8]),
 tensor([[ 0.5466,  1.9774, -0.2422,  1.8863,  1.4273, -0.2646,  1.5859,  2.1209],
         [-0.7454, -0.8438,  2.9146, -0.0053,  1.1575, -1.2436,  0.1926,  0.3608],
         [ 1.7229, -0.1413, -1.9222, -1.0064, -1.2585, -1.3769,  2.0752,  2.1619]]))

In [141]:
layer_norm = LayerNormalization(inputs.size()[-1:])
out = layer_norm.forward(inputs)
# out 

Mean :  torch.Size([5, 3, 1]) tensor([[[ 1.1297],
         [ 0.2234],
         [ 0.0318]],

        [[-0.5829],
         [-0.0419],
         [ 0.0219]],

        [[-0.2787],
         [-0.0486],
         [-0.0353]],

        [[ 0.2828],
         [ 0.8355],
         [ 0.1275]],

        [[ 0.3711],
         [-0.0401],
         [ 0.0690]]])
STD:  torch.Size([5, 3, 1]) tensor([[[0.9176],
         [1.2458],
         [1.5870]],

        [[1.2928],
         [1.1881],
         [0.5851]],

        [[0.8185],
         [0.6662],
         [1.1070]],

        [[1.2932],
         [0.6500],
         [0.9273]],

        [[0.7234],
         [1.1516],
         [1.1884]]])
y:  torch.Size([5, 3, 8]) tensor([[[-0.6354,  0.9237, -1.4951,  0.8245,  0.3243, -1.5194,  0.4972,
           1.0801],
         [-0.7776, -0.8566,  2.1602, -0.1836,  0.7497, -1.1775, -0.0248,
           0.1103],
         [ 1.0656, -0.1091, -1.2313, -0.6542, -0.8131, -0.8877,  1.2876,
           1.3422]],

        [[-2.0630,  1.0763,  0

In [142]:
import torch

# Sample data (categorical labels)
labels = torch.tensor([1, 0, 3, 1])  # Example labels (categories)
labels


tensor([1, 0, 3, 1])

In [143]:
num_categories = labels.max() + 1
num_categories

tensor(4)

In [144]:
one_hot = torch.nn.functional.one_hot(labels, num_classes=num_categories)
one_hot

tensor([[0, 1, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 1, 0, 0]])