In [4]:
x = [[1,2,3],[3,2,15],[1,18,21]]

mini = float('inf')
maxi = float('-inf')

for i in x:
    for j in i:
        if j<mini:
            mini = j
        
        if j>maxi:
            maxi = j

print(mini,maxi)

1 21


In [5]:
new  = [[0]*3]*3

for i in range(3):
    for j in range(3):
        new[i][j] = (x[i][j] - mini) /(maxi-mini)

new

[[0.0, 0.85, 1.0], [0.0, 0.85, 1.0], [0.0, 0.85, 1.0]]

## column standardlization

In [6]:
X = [[4,8,13,7],[11,4,5,14]]
mean_x1 = sum(X[0]) / len(X[0])
mean_x2 = sum(X[1]) / len(X[1])
mean_x1, mean_x2

(8.0, 8.5)

In [11]:
import numpy as np 

var_x1 = (np.var(X[0]))*4 // 3
var_x2 = np.var(X[1])*4 // 3

var_x1, var_x2

(14.0, 23.0)

In [13]:
np.cov(X)

array([[ 14., -11.],
       [-11.,  23.]])

In [14]:
from sklearn.preprocessing import StandardScaler   
standardized_data = StandardScaler().fit_transform(X)    

In [15]:
standardized_data

array([[-1.,  1.,  1., -1.],
       [ 1., -1., -1.,  1.]])

In [17]:
covar_mat = np.cov(standardized_data)
covar_mat

array([[ 1.33333333, -1.33333333],
       [-1.33333333,  1.33333333]])

In [24]:
co_var_matrix = np.matmul(standardized_data, standardized_data.T) /3
co_var_matrix

array([[ 1.33333333, -1.33333333],
       [-1.33333333,  1.33333333]])